'use client'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Login from './page'
import NavBar from '../components/Navbar/navBar'
import { AuthProvider } from '@/context/auth'
import { ReactNode } from 'react'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Orkut',
  description: 'Generated by create next app',
}

interface ChildrenProps{
  children: React.FC<ReactNode> 
}

export default function RootLayout({children}: ChildrenProps) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
              {children}
        </AuthProvider>
        </body>
    </html>
  )
}
